"nbdkit [-4|--ipv4-only] [-6|--ipv6-only]\n"
"       [-D|--debug PLUGIN|FILTER|nbdkit.FLAG=N]\n"
"       [--exit-with-parent] [-e|--exportname EXPORTNAME]\n"
"       [--filter=FILTER ...] [-f|--foreground]\n"
"       [-g|--group GROUP] [-i|--ipaddr IPADDR]\n"
"       [--log=stderr|syslog|null] [--mask-handshake=MASK]\n"
"       [-n|--newstyle] [--no-sr] [-o|--oldstyle]\n"
"       [-P|--pidfile PIDFILE] [-p|--port PORT]\n"
"       [-r|--readonly] [--run 'COMMAND ARGS ...']\n"
"       [--selinux-label=LABEL] [-s|--single] [--swap]\n"
"       [-t|--threads THREADS] [--tls=off|on|require]\n"
"       [--tls-certificates=/path/to/certificates]\n"
"       [--tls-psk=/path/to/pskfile] [--tls-verify-peer]\n"
"       [-U|--unix SOCKET|-] [-u|--user USER]\n"
"       [-v|--verbose] [--vsock]\n"
"       PLUGIN [[KEY=]VALUE [KEY=VALUE [...]]]\n"
"\n"
"nbdkit --dump-config\n"
"\n"
"nbdkit PLUGIN --dump-plugin\n"
"\n"
"nbdkit --help\n"
"\n"
"nbdkit [-V|--version]\n"
